---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: "httptogrpc-v0-1-0-snapshot"
  labels:
    appName: httptogrpc
    appNameVersion: "httptogrpc-v0-1-0-snapshot"
spec:
  replicas: 1
  selector:
    matchLabels:
      appNameVersion: "httptogrpc-v0-1-0-snapshot"
  template:
    metadata:
      labels:
        appName: httptogrpc
        appNameVersion: "httptogrpc-v0-1-0-snapshot"
    spec:
      restartPolicy: Always
      containers:
        - name: httptogrpc
          image: "httptogrpc:0.1.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts: []
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    appName: httptogrpc
  name: httptogrpc
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    appName: httptogrpc
---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: httptogrpc
spec:
  rules:
    - host: "superservice.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: httptogrpc
                port:
                  number: 8080